CREATE DATABASE IF NOT EXISTS tp2_tareas;

USE tp2_tareas;

CREATE TABLE tareas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    completada BOOLEAN NOT NULL DEFAULT FALSE
);